import type { Listing } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ListingCard } from "~/components/ListingCard";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading: listingsLoading } = api.listing.getAll.useQuery();
  
  if (listingsLoading) return <div>Loading...</div>
  console.log(data);
  if (!data) return <div>No Listings</div>

  return (
    <>
      <Head>
        <title>Venari</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#AE8E7E] to-[#54504A]">
        <h1 className="text-4xl">Hunts Available</h1>
        <div className="container grid grid-cols-3 items-center justify-center gap-12 px-4 py-16 ">
          {data?.map((listing) => <ListingCard {...listing} key={listing.listing.id} />)}
        </div>
      </main>
    </>
  );
};

export default Home;
